osx_image: xcode8
language: objective-c
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
- set -o pipefail && xcodebuild build -workspace Example/OcticonsKit.xcworkspace -scheme OcticonsKit-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint --quick
- carthage build --platform iOS --no-skip-current
